#端口号配置
server:
  port: 8082

#数据库配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/prj02?serverTimezone=UTC
    username: root
    password: 123456

#映射mapper包
mybatis:
  mapper-locations: classpath:mapper/*.xml